import assert from "node:assert/strict";
import test from "node:test";

import {
  compileSqlForbiddenEffectObligations,
  ForbiddenEffectEnvironment,
  ForbiddenEffectEvidenceType,
  ForbiddenEffectFailClosedAction,
  ForbiddenEffectObligationSchema,
  SqlForbiddenEffectObligationKind,
  SqlForbiddenEffectOperation,
} from "@agent-safety-gateway/shared/forbidden-side-effect";

const assertValidObligations = (obligations) => {
  for (const obligation of obligations) {
    const result = ForbiddenEffectObligationSchema.safeParse(obligation);

    assert.equal(result.success, true);
  }
};

const findObligationByKind = (obligations, kind) => {
  const obligation = obligations.find((candidate) =>
    candidate.obligationId.includes(`-${kind}-`),
  );

  assert.ok(obligation, `Expected obligation kind ${kind}`);

  return obligation;
};

test("compiles readonly SELECT into mutation, DDL, trigger, and external-effect obligations", () => {
  const result = compileSqlForbiddenEffectObligations({
    requestId: "req-sql-read-orders",
    requestHash: "sha256:readonly-orders-request",
    sql: `
      /* generated by agent */
      SELECT o.id, c.email
      FROM public.orders o
      JOIN customers c ON c.id = o.customer_id
      WHERE o.status = 'PENDING'
    `,
    environment: ForbiddenEffectEnvironment.Production,
    createdAt: "2026-05-01T06:30:00.000Z",
  });

  assert.equal(result.operation, SqlForbiddenEffectOperation.Select);
  assert.equal(result.failClosed, false);
  assert.deepEqual(result.unresolvedTables, []);
  assert.deepEqual(result.resourceScope, ["orders", "customers"]);
  assert.equal(result.obligations.length, 4);
  assertValidObligations(result.obligations);

  const mutation = findObligationByKind(
    result.obligations,
    SqlForbiddenEffectObligationKind.ReadonlyMutation,
  );
  assert.deepEqual(mutation.requiredEvidenceTypes, [
    ForbiddenEffectEvidenceType.WriteDenial,
    ForbiddenEffectEvidenceType.DeleteDenial,
    ForbiddenEffectEvidenceType.NoRowMutation,
  ]);
  assert.deepEqual(mutation.forbiddenCapabilities, [
    "insert",
    "update",
    "delete",
    "write",
    "mutation",
  ]);

  const ddl = findObligationByKind(
    result.obligations,
    SqlForbiddenEffectObligationKind.ReadonlyDdl,
  );
  assert.deepEqual(ddl.requiredEvidenceTypes, [
    ForbiddenEffectEvidenceType.DdlDenial,
  ]);
  assert.deepEqual(ddl.forbiddenCapabilities, [
    "drop",
    "truncate",
    "alter",
    "ddl",
  ]);

  const trigger = findObligationByKind(
    result.obligations,
    SqlForbiddenEffectObligationKind.ReadonlyTrigger,
  );
  assert.deepEqual(trigger.requiredEvidenceTypes, [
    ForbiddenEffectEvidenceType.NoTriggerSideEffect,
  ]);

  const external = findObligationByKind(
    result.obligations,
    SqlForbiddenEffectObligationKind.ReadonlyExternalEffect,
  );
  assert.deepEqual(external.requiredEvidenceTypes, [
    ForbiddenEffectEvidenceType.NoExternalSideEffect,
  ]);
  assert.deepEqual(external.forbiddenEffects, [
    "external_side_effect",
    "async_job",
    "webhook",
  ]);

  for (const obligation of result.obligations) {
    assert.equal(
      obligation.failClosedAction,
      ForbiddenEffectFailClosedAction.DenyPermit,
    );
    assert.equal(obligation.requiredExecutionMode, "readonly");
    assert.deepEqual(obligation.resourceScope, ["orders", "customers"]);
    assert.equal(obligation.requestHash, "sha256:readonly-orders-request");
  }
});

test("compiles destructive SQL operations into fail-closed destructive obligations", () => {
  const cases = [
    {
      sql: "DELETE FROM orders WHERE status = 'PENDING'",
      operation: SqlForbiddenEffectOperation.Delete,
      kind: SqlForbiddenEffectObligationKind.DestructiveMutation,
      evidenceType: ForbiddenEffectEvidenceType.DeleteDenial,
    },
    {
      sql: "UPDATE orders SET status = 'CANCELLED' WHERE id = 42",
      operation: SqlForbiddenEffectOperation.Update,
      kind: SqlForbiddenEffectObligationKind.DestructiveMutation,
      evidenceType: ForbiddenEffectEvidenceType.WriteDenial,
    },
    {
      sql: "INSERT INTO orders (id, status) VALUES (42, 'PENDING')",
      operation: SqlForbiddenEffectOperation.Insert,
      kind: SqlForbiddenEffectObligationKind.DestructiveMutation,
      evidenceType: ForbiddenEffectEvidenceType.WriteDenial,
    },
    {
      sql: "DROP TABLE IF EXISTS orders",
      operation: SqlForbiddenEffectOperation.Drop,
      kind: SqlForbiddenEffectObligationKind.DestructiveDdl,
      evidenceType: ForbiddenEffectEvidenceType.DdlDenial,
    },
    {
      sql: "TRUNCATE TABLE orders",
      operation: SqlForbiddenEffectOperation.Truncate,
      kind: SqlForbiddenEffectObligationKind.DestructiveDdl,
      evidenceType: ForbiddenEffectEvidenceType.DdlDenial,
    },
    {
      sql: "ALTER TABLE orders ADD COLUMN audit_note text",
      operation: SqlForbiddenEffectOperation.Alter,
      kind: SqlForbiddenEffectObligationKind.DestructiveDdl,
      evidenceType: ForbiddenEffectEvidenceType.DdlDenial,
    },
  ];

  for (const item of cases) {
    const result = compileSqlForbiddenEffectObligations({
      requestId: `req-sql-${item.operation}`,
      sql: item.sql,
      environment: ForbiddenEffectEnvironment.Production,
    });

    assert.equal(result.operation, item.operation);
    assert.equal(result.failClosed, false);
    assert.deepEqual(result.resourceScope, ["orders"]);
    assert.equal(result.obligations.length, 1);
    assertValidObligations(result.obligations);

    const [obligation] = result.obligations;
    assert.ok(obligation.obligationId.includes(`-${item.kind}-`));
    assert.equal(obligation.requiredExecutionMode, "deny_destructive_sql");
    assert.deepEqual(obligation.forbiddenCapabilities, [
      item.operation,
      "destructive_sql",
    ]);
    assert.equal(
      obligation.requiredEvidenceTypes.includes(item.evidenceType),
      true,
    );
    assert.equal(
      obligation.requiredEvidenceTypes.includes(
        ForbiddenEffectEvidenceType.NoExternalSideEffect,
      ),
      true,
    );
    assert.equal(
      obligation.failClosedAction,
      ForbiddenEffectFailClosedAction.DenyPermit,
    );
  }
});

test("compiles unresolved SQL targets into uncertainty obligations that fail closed", () => {
  const result = compileSqlForbiddenEffectObligations({
    requestId: "req-sql-unresolved-table",
    sql: "SELECT 1",
    environment: ForbiddenEffectEnvironment.Production,
  });

  assert.equal(result.operation, SqlForbiddenEffectOperation.Select);
  assert.equal(result.failClosed, true);
  assert.deepEqual(result.resourceScope, ["unresolved_sql_resource"]);
  assert.deepEqual(result.unresolvedTables, ["unresolved_sql_resource"]);
  assert.equal(result.obligations.length, 1);
  assertValidObligations(result.obligations);

  const [obligation] = result.obligations;
  assert.ok(
    obligation.obligationId.includes(
      `-${SqlForbiddenEffectObligationKind.UnresolvedResource}-`,
    ),
  );
  assert.equal(obligation.requiredExecutionMode, "fail_closed");
  assert.deepEqual(obligation.requiredEvidenceTypes, [
    ForbiddenEffectEvidenceType.WriteDenial,
    ForbiddenEffectEvidenceType.DeleteDenial,
    ForbiddenEffectEvidenceType.DdlDenial,
    ForbiddenEffectEvidenceType.NoRowMutation,
    ForbiddenEffectEvidenceType.NoTriggerSideEffect,
    ForbiddenEffectEvidenceType.NoExternalSideEffect,
  ]);
  assert.deepEqual(obligation.forbiddenCapabilities, [
    "unknown_sql_operation",
    "unresolved_table",
    "write",
    "delete",
    "ddl",
  ]);
  assert.deepEqual(obligation.forbiddenEffects, [
    "unknown_sql_side_effect",
    "row_mutation",
    "trigger_side_effect",
    "external_side_effect",
  ]);
  assert.equal(
    obligation.failClosedAction,
    ForbiddenEffectFailClosedAction.DenyPermit,
  );
});
